name: beheer_task_manager
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  get: 4.6.5
  google_fonts: 5.1.0
  intl: 0.18.1
  readmore: ^2.2.0
  unicons: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/bold/
    - assets/icon/linear/
